### ISSUE TITLE
GUI freezes (?) upon startup

### ISSUE THREAD

**Issue by RadsammyT** [Jpe230/BOTW-Save-Editor-GUI#12]
After complying with the instruction to open/close BOTW, (CFW: Atmo latest as of 12/25/19) I am greeted with the Master Mode save file, but without any control input response, however I can still go to HOME.
Latest sys updates, and FW Ver (9.1.0).
Is there something wrong?

**Comment by RadsammyT** [comment]
Forgot to mention: Latest sys updates, and FW Ver (9.1.0).

**Comment by bambam090** [comment]
@Jpe230, @RadsammyT is having the same problem I am

**Comment by ghost** [comment]
I have the same problem too. Why is that? Can it be Fixed?

**Comment by moonBright-halcyonDays** [comment]
I'm having the same issue
