### ISSUE TITLE
I Have NO idea how to run this:

### ISSUE THREAD

**Issue by ghost** [Jpe230/BOTW-Save-Editor-GUI#4]
I used homebrew but it just is not in the format of nro (I think) so what do I use

**Comment by Nate-GIS** [comment]
1: Please download the .nro file from https://github.com/Jpe230/BOTW-Save-Editor-GUI/releases/latest

2: Paste the file on your switch's SD card under the folder "switch"

3: Should load up fine.

What cfw are you using to access homebrew?

**Comment by ghost** [comment]
Thx
much better
not sure witch one
